<div class="container-editar-genero">
    <h1>Editar Género</h1>
    <form method="POST">
        <label for="genero">Nombre del Género:</label>
        <input type="text" name="genero" id="genero" value="<?= htmlspecialchars($genero, ENT_QUOTES, 'UTF-8') ?>" required>
        <input type="submit" value="Cambiar">
    </form>
    <a href="<?= BASE_URL ?>listarCategorias">Volver</a>
</div>
