<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Librería</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>

<body>

    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link active" aria-current="page" href="<?= BASE_URL ?>libros">Libros</a>
                    <a class="nav-link" href="<?= BASE_URL ?>listarCategorias">Géneros</a>
                    <a class="nav-link" href="<?= BASE_URL ?>login">Log In</a>
                </div>
            </div>
        </div>
    </nav>

    <div class="container-porCategoria mt-5">
    <h1 class="text-center text-secondary">Libros del género: <span class="text-uppercase"><?= $genero ?></span></h1>
    
    <div class="d-flex justify-content-center">
        <ul class="list-group list-group-flush mt-4" style="max-width: 900px;">
            <?php foreach($libros as $libro) : ?>
                <li class="list-group-item d-flex justify-content-between align-items-center border-0">
                    <div class="w-100 d-flex justify-content-between align-items-center">
                        <div>
                            <a href="<?= BASE_URL ?>detallarLibro/<?= $libro->id_libro ?>" class="text-decoration-none text-dark fw-bold">
                                <?= $libro->titulo ?>
                            </a>
                            <small class="d-block text-muted"><?= $libro->autor ?></small>
                        </div>
                        <span class="text-muted ms-3"><?= $libro->precio ?>€</span>
                    </div>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>

    <div class="text-center mt-4">
        <a href="<?= BASE_URL ?>listarCategorias" class="btn btn-outline-secondary">Volver a Categorías</a>
    </div>
</div>


    

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous">
    </script>
</body>

</html>