

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Librería</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>

<body>

    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link active" aria-current="page" href="<?= BASE_URL ?>libros">Libros</a>
                    <a class="nav-link" href="<?= BASE_URL ?>listarCategorias">Géneros</a>
                    <a class="nav-link" href="<?= BASE_URL ?>login">Log In</a>
                </div>
            </div>
        </div>
    </nav>

    <div class="container mt-5">
        <h1 class="text-center mb-4">Detalle de Libro</h1>
        
        <div class="card">
            <div class="card-body">
                <p><strong>Título:</strong> <?= htmlspecialchars($libro->titulo, ENT_QUOTES, 'UTF-8') ?></p>
                <p><strong>Autor:</strong> <?= htmlspecialchars($libro->autor, ENT_QUOTES, 'UTF-8') ?></p>
                <p><strong>Precio:</strong> $ <?= htmlspecialchars($libro->precio, ENT_QUOTES, 'UTF-8') ?> </p>
                <p><strong>Categoría:</strong> <?= htmlspecialchars($libro->genero, ENT_QUOTES, 'UTF-8') ?></p>
                <p><strong>Editorial:</strong> <?= htmlspecialchars($libro->editorial, ENT_QUOTES, 'UTF-8') ?></p>
                
                <div class="mt-4">
                    <a href="<?= BASE_URL ?>editarLibro/<?= htmlspecialchars($libro->id_libro, ENT_QUOTES, 'UTF-8') ?>" class="btn btn-warning">Editar</a>
                    <a href="<?= BASE_URL ?>eliminarLibro/<?= htmlspecialchars($libro->id_libro, ENT_QUOTES, 'UTF-8') ?>/" class="btn btn-danger">Eliminar</a>
                    <a href="<?= BASE_URL ?>libros" class="btn btn-secondary">Volver</a>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous">
    </script>
</body>

</html>
