<div class="container-detalle-libro">
    <h1>Detalle de Libro</h1>
    
    <p><strong>Título:</strong> <?= htmlspecialchars($libro->titulo, ENT_QUOTES, 'UTF-8') ?></p>
    <p><strong>Autor:</strong> <?= htmlspecialchars($libro->autor, ENT_QUOTES, 'UTF-8') ?></p>
    <p><strong>Precio:</strong> $ <?= htmlspecialchars($libro->precio, ENT_QUOTES, 'UTF-8') ?> </p>
    <p><strong>Categoría:</strong> <?= htmlspecialchars($libro->genero, ENT_QUOTES, 'UTF-8') ?></p>
    <p><strong>Editorial:</strong> <?= htmlspecialchars($libro->editorial, ENT_QUOTES, 'UTF-8') ?></p>
    <a href="<?= BASE_URL ?>editarLibro/<?= htmlspecialchars($libro->id_libro, ENT_QUOTES, 'UTF-8') ?>">Editar</a>
    <a href="<?= BASE_URL ?>eliminarLibro/<?= htmlspecialchars($libro->id_libro, ENT_QUOTES, 'UTF-8') ?>/">Eliminar</a>

    <a href="<?= BASE_URL ?>libros">Volver</a>


</div>

