<div class="container-editar-libro">
    <h1>Editar Libro</h1>
    <form method="POST" <?= htmlspecialchars($libro->id_libro, ENT_QUOTES, 'UTF-8') ?>>
        <label for="titulo">Titulo:</label>
        <input type="text" name="titulo" id="titulo" value="<?= htmlspecialchars($libro->titulo, ENT_QUOTES, 'UTF-8') ?>" required>

        <label for="autor">Autor:</label>
        <input type="text" name="autor" id="autor" value="<?= htmlspecialchars($libro->autor, ENT_QUOTES, 'UTF-8') ?>" required>

        <label for="precio">Precio:</label>
        <input type="number" name="precio" id="precio" value="<?= htmlspecialchars($libro->precio, ENT_QUOTES, 'UTF-8') ?>" required>

        <label for="genero">Genero:</label>
        <select name="genero" id="genero" required>
            <?php foreach ($categorias as $categoria): ?>
                <option value="<?= htmlspecialchars($categoria['genero'], ENT_QUOTES, 'UTF-8') ?>" <?= $categoria['genero'] === $libro->genero ? 'selected' : '' ?>>
                    <?= htmlspecialchars($categoria['genero'], ENT_QUOTES, 'UTF-8') ?>
                </option>
            <?php endforeach; ?>
        </select>
        <input type="submit" value="Cambiar">
    </form>
    <a href="<?= BASE_URL ?>libros">Volver</a>
</div>
